### ISSUE TITLE
Not working after upgrading to 0.8.X on HA 0.118.2 with python3.8 (venv)

### ISSUE THREAD

**Issue by BornTKill** [custom-components/ble_monitor#165]
Dear,

Everything was OK when < 0.8 but now I get this error : 

2020-11-22 00:15:06 ERROR (Thread-7) [root] Uncaught thread exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/home/homeassistant/.homeassistant/custom_components/ble_monitor/sensor.py", line 585, in run
    mysocket[hci] = aiobs.create_bt_socket(hci)
  File "/home/homeassistant/.homeassistant/custom_components/ble_monitor/aioblescan_ext.py", line 1382, in create_bt_socket
    sock = socket.socket(family=socket.AF_BLUETOOTH,
AttributeError: module 'socket' has no attribute 'AF_BLUETOOTH'

I have just upgraded HA to 0.118.2 with python3.8 and after that your component.
Permissions :

root@homeassistant:/home/homeassistant/.homeassistant/custom_components# sudo getcap `readlink -f /usr/local/bin/python3.8`
/usr/local/bin/python3.8 = cap_net_admin,cap_net_raw+eip
root@homeassistant:/home/homeassistant/.homeassistant/custom_components# sudo getcap `readlink -f /opt/homeassistant/bin/python3.8`
/usr/local/bin/python3.8 = cap_net_admin,cap_net_raw+eip
root@homeassistant:/home/homeassistant/.homeassistant/custom_components# sudo getcap `readlink -f \`which python3\``
/usr/bin/python3.7 = cap_net_admin,cap_net_raw+eip

My conf :

ble_monitor:
  rounding: True
  decimals: 1
  period: 60
  log_spikes: False
  use_median: False
  active_scan: False
  hci_interface: 0
  batt_entities: True
  discovery: True
  report_unknown: False

Thank you for your help.
Best regards.

**Comment by BornTKill** [comment]
Seem to have to compile python with BT support. but how ?

**Comment by Ernst79** [comment]
You didn’t include Bluetooth support in python. See for the solution the last response in this issue #151

**Comment by BornTKill** [comment]
Hi! Thank you. That solved the issue.
