### ISSUE TITLE
Xiaomi Mija Mosquito Repellent WX08ZM

### ISSUE THREAD

**Issue by rafkan20** [custom-components/ble_monitor#275]
After upgrading to 1.0.4 an error occurred:

Logger: homeassistant.helpers.entity
Source: custom_components/ble_monitor/sensor.py:673
First occurred: 22:45:22 (9 occurrences)
Last logged: 22:53:23

Update for sensor.ble_consumable_na_komary fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 278, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 474, in async_device_update
    raise exc
  File "/config/custom_components/ble_monitor/sensor.py", line 673, in async_update
    self._state = self._newstate
AttributeError: 'ConsumableSensor' object has no attribute '_newstate'

**Comment by Ernst79** [comment]
Thanks, for reporting. I released 1.0.5-beta which should fix this issue.

**Comment by rafkan20** [comment]
It works, thank you.

**Comment by Ernst79** [comment]
No, BLE monitor is a passive BLE component, so the only thing it does is listening. Turning things on/off requires sending BLE messages, which is (at the moment) out of the scope of this component. 

May be in the future, But I don't expect this to happen very soon. 

P.S. 1.0.5 final has been released, so I'm closing this issue.
