### ISSUE TITLE
MCCGQ02HL not work in 5.3.0

### ISSUE THREAD

**Issue by andrewjswan** [custom-components/ble_monitor#512]
Motion and Light sensor not updating...
In log:
```
Эта ошибка возникла в кастомной интеграции.

Logger: homeassistant
Source: custom_components/ble_monitor/ble_parser/xiaomi.py:763
Integration: Passive BLE monitor (documentation, issues)
First occurred: 19:08:34 (4 occurrences)
Last logged: 19:11:52

Error doing job: Fatal error: protocol.data_received() call failed.
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/asyncio/selector_events.py", line 870, in _read_ready__data_received
    self._protocol.data_received(data)
  File "/usr/local/lib/python3.9/site-packages/aioblescan/aioblescan.py", line 1852, in data_received
    self.process(packet)
  File "/config/custom_components/ble_monitor/__init__.py", line 567, in process_hci_events
    sensor_msg, tracker_msg = self.ble_parser.parse_data(data)
  File "/config/custom_components/ble_monitor/ble_parser/__init__.py", line 88, in parse_data
    sensor_data = parse_xiaomi(self, adstruct, mac, rssi)
  File "/config/custom_components/ble_monitor/ble_parser/xiaomi.py", line 763, in parse_xiaomi
    result.update(resfunc(object))
TypeError: obj000f() missing 1 required positional argument: 'device_type'
```

**Comment by andrewjswan** [comment]
Rollback to 5.2.1

**Comment by Ernst79** [comment]
Fixed in 5.3.1, see also #511
