### ISSUE TITLE
Not work after update to 1.7.3 build

### ISSUE THREAD

**Issue by migor7** [custom-components/ble_monitor#336]
After upgrade to 1.7.3 in log:

Traceback (most recent call last):
  File "/etc/homeassistant/custom_components/ble_monitor/binary_sensor.py", line 125, in async_run
    dev = dev_registry.async_get_device(identifiers={(DOMAIN, mac)})
TypeError: async_get_device() missing 1 required positional argument: 'connections'

**Comment by hugalafutro** [comment]
What version were you updating from? I'm on 1.8.3beta and I;m being offered 1.7.3 as update.

Was 1.8.3beta pulled ?

**Comment by migor7** [comment]
> What version were you updating from? I'm on 1.8.0beta and I;m being offered 1.7.3 as update.

From 1.7.0

**Comment by Ernst79** [comment]
@migor7 how did you configure BLE monitor? In Yaml or in the UI?

can you show me your configuration?

@hugalafutro 1.7.3 was released after 1.8.0-beta, as a quick fix was needed on 1.7.x. 1.8.x is under development (not finished).  The same fix as in 1.7.3 is added in 1.8.2-beta, which was released an hour ago.

**Comment by migor7** [comment]
> @migor7 how did you configure BLE monitor? In Yaml or in the UI?
> 
> can you show me your configuration?
> 
> @hugalafutro 1.7.3 was released after 1.8.0-beta, as a quick fix was needed on 1.7.x. 1.8.x is under development (not finished). The same fix as in 1.7.3 is added in 1.8.2-beta, which was released an hour ago.

ble_monitor:
  discovery: False
  active_scan: False
  report_unknown: False
  batt_entities: True
  decimals: 1
  period: 60
  log_spikes: False
  use_median: False
  restore_state: False
  devices:
    - mac: 'xx'
      name: 'room'
      encryption_key: xx'
      temperature_unit: C
      decimals: 2
      use_median: False
      restore_state: default
    - mac: 'xx
      name: 'kitchen'
      encryption_key: 'xx'
      temperature_unit: C
      decimals: 2
      use_median: False
      restore_state: default
    - mac: 'xx'
      name: 'bathroom'
      encryption_key: 'xx'
      temperature_unit: C
      decimals: 2
      use_median: False
      restore_state: default

**Comment by Ernst79** [comment]
Can you try another restart of HA, with debug enabled and post the logs here?

```
logger:
  default: warn
  logs:
    custom_components.ble_monitor: debug
```

**Comment by migor7** [comment]
> Can you try another restart of HA, with debug enabled and post the logs here?
> 
> ```
> logger:
>   default: warn
>   logs:
>     custom_components.ble_monitor: debug
> ```
DEBUG (MainThread) [custom_components.ble_monitor] Initializing BLE Monitor entry (config entry): <homeassistant.config_entries.ConfigEntry object at 0x2ea6380>
2021-04-27 23:12:39 DEBUG (MainThread) [custom_components.ble_monitor] async_setup_entry: domain {'discovery': False, 'active_scan': False, 'report_unknown': False, 'batt_entities': True, 'decimals': 1, 'period': 60, 'log_spikes': False, 'use_median': False, 'restore_state': False, 'devices': [{'mac': 'xx, 'name': 'room', 'encryption_key': 'xx', 'temperature_unit': '°C', 'decimals': 2, 'use_median': False, 'restore_state': 'default', 'reset_timer': 35}, {'mac': 'xx', 'name': 'kitchen', 'encryption_key': 'xx', 'temperature_unit': '°C', 'decimals': 2, 'use_median': False, 'restore_state': 'default', 'reset_timer': 35}, {'mac': 'xx', 'name': 'bathroom', 'encryption_key': 'xx', 'temperature_unit': '°C', 'decimals': 2, 'use_median': False, 'restore_state': 'default', 'reset_timer': 35}], 'hci_interface': [], 'rounding': 1, 'bt_interface': ['xx'], 'is_flow': False, 'ids_from_name': True}
2021-04-27 23:12:39 WARNING (MainThread) [custom_components.ble_monitor] Available Bluetooth interfaces for BLE monitor: ['xx]
2021-04-27 23:12:39 DEBUG (MainThread) [custom_components.ble_monitor] async_setup_entry: {'discovery': False, 'active_scan': False, 'report_unknown': False, 'batt_entities': True, 'decimals': 1, 'period': 60, 'log_spikes': False, 'use_median': False, 'restore_state': False, 'devices': [{'mac': 'A4:C1:38:63:B1:53', 'name': 'room', 'encryption_key': '44748cbea0b2187917abf03435773a0a', 'temperature_unit': '°C', 'decimals': 2, 'use_median': False, 'restore_state': 'default', 'reset_timer': 35}, {'mac': 'a4:c1:38:d7:31:23', 'name': 'kitchen', 'encryption_key': '39a4f2392be01c6744e5ce4c4ca7dc49', 'temperature_unit': '°C', 'decimals': 2, 'use_median': False, 'restore_state': 'default', 'reset_timer': 35}, {'mac': 'a4:c1:38:f3:f1:eb', 'name': 'bathroom', 'encryption_key': '1d70aa0646fe764c2f41d9ae0a312420', 'temperature_unit': '°C', 'decimals': 2, 'use_median': False, 'restore_state': 'default', 'reset_timer': 35}], 'hci_interface': [0], 'rounding': 1, 'bt_interface': ['38:83:9A:13:9C:CB'], 'is_flow': False, 'ids_from_name': True}
2021-04-27 23:12:39 DEBUG (MainThread) [custom_components.ble_monitor] HCI interface is [0]
2021-04-27 23:12:39 DEBUG (MainThread) [custom_components.ble_monitor] Spawning HCIdump thread
2021-04-27 23:12:39 DEBUG (MainThread) [custom_components.ble_monitor] HCIdump thread: Init
2021-04-27 23:12:39 DEBUG (MainThread) [custom_components.ble_monitor] 3 encryptors mac:key pairs loaded.
2021-04-27 23:12:39 DEBUG (MainThread) [custom_components.ble_monitor] whitelist: [xx, xx, xx]
2021-04-27 23:12:39 DEBUG (MainThread) [custom_components.ble_monitor] 3 whitelist item(s) loaded.
2021-04-27 23:12:39 DEBUG (Thread-3) [custom_components.ble_monitor] HCIdump thread: Run
2021-04-27 23:12:39 DEBUG (Thread-3) [custom_components.ble_monitor] HCIdump thread: connected to hci0
2021-04-27 23:12:40 DEBUG (Thread-3) [custom_components.ble_monitor] HCIdump thread: start main event_loop
2021-04-27 23:12:55 DEBUG (MainThread) [custom_components.ble_monitor.sensor] Starting measuring sensor entry startup
2021-04-27 23:12:55 DEBUG (MainThread) [custom_components.ble_monitor.sensor] BLE sensors updater initialization
2021-04-27 23:12:55 DEBUG (MainThread) [custom_components.ble_monitor.sensor] BLE sensors updater initialized
2021-04-27 23:12:55 DEBUG (MainThread) [custom_components.ble_monitor.sensor] Measuring sensor entry setup finished
2021-04-27 23:12:55 DEBUG (MainThread) [custom_components.ble_monitor.sensor] Entities updater loop started!
2021-04-27 23:12:55 DEBUG (MainThread) [custom_components.ble_monitor.binary_sensor] Starting binary sensor entry startup
2021-04-27 23:12:55 DEBUG (MainThread) [custom_components.ble_monitor.binary_sensor] BLE binary sensors updater initialization
2021-04-27 23:12:55 DEBUG (MainThread) [custom_components.ble_monitor.binary_sensor] BLE binary sensors updater initialized
2021-04-27 23:12:55 DEBUG (MainThread) [custom_components.ble_monitor.binary_sensor] Binary sensor entry setup finished
2021-04-27 23:12:56 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/etc/homeassistant/custom_components/ble_monitor/sensor.py", line 168, in async_run
    dev = dev_registry.async_get_device(identifiers={(DOMAIN, mac)})
TypeError: async_get_device() missing 1 required positional argument: 'connections'
2021-04-27 23:12:56 DEBUG (MainThread) [custom_components.ble_monitor.binary_sensor] Binary entities updater loop started!
2021-04-27 23:12:57 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/etc/homeassistant/custom_components/ble_monitor/binary_sensor.py", line 125, in async_run
    dev = dev_registry.async_get_device(identifiers={(DOMAIN, mac)})
TypeError: async_get_device() missing 1 required positional argument: 'connections'

**Comment by Ernst79** [comment]
I'll look into it.

**Comment by adisik** [comment]
Hi, i have same error on versions 1.7.3 and 1.8.2-beta.
2021-04-28 10:07:44 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
File "/etc/homeassistant/custom_components/ble_monitor/sensor.py", line 172, in async_run
dev = dev_registry.async_get_device(identifiers={(DOMAIN, mac)})
TypeError: async_get_device() missing 1 required positional argument: 'connections'

**Comment by Ernst79** [comment]
Strange thing is that I can't reproduce the issue on my systems, even with the same configuration. 
I would like to ask you to test the following solution. 

In `sensor.py` line 168 and `binary_sensor.py` line 125 (in the custom_components/ble_monitor folder) look for the following text. Line number can be slightly different in 1.8.2-beta

```
dev = dev_registry.async_get_device(identifiers={(DOMAIN, mac)})
```

and try to change these lines in both files to the following
```
dev = dev_registry.async_get_device({(DOMAIN, mac)}, set())
```

Afterwards, please restart and let me know if this fixes the issue

**Comment by adisik** [comment]
@Ernst79 ,I changed these lines in both files and problem solved. There is no error in the log and the sensors are working

**Comment by Ernst79** [comment]
Great, thanks for testing. 1.7.4 has been released. 

1.8.x will follow tonight with the same fix.
